---
title: "Info about the OSCA study programme"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The *Operations and Supply Chain Analytics* program {#OSCA}

*Operations and Supply Chain Management* (OSCM) includes a broad area covering both manufacturing and service industries, and it involves functions such as sourcing, materials management, operations planning, distribution, logistics, retail, demand forecasting, order fulfillment, and more.


*Analytics* refers to the scientific process of transforming data into insights for making better decisions in businesses (Definition of [INFORMS.org](https://www.informs.org/About-INFORMS/News-Room/O.R.-and-Analytics-in-the-News/Best-definition-of-analytics)). 

**Operations and Supply Chain Analytics** (our program) refers to the application of the tools from analytics to handle O&SCM problems such as

* Big data management:
    * Storing, integrating, analyzing, updating, and using huge amounts of data in real time.
* Data driven decision making:
    * The process of making decisions based on actual data rather than intuition or observation alone.
* Optimization of business process:
    * Mathematical methods to find a best solution to a particular type of problem with respect to a set of desired criteria. 
* Computer simulations for business process improvement:
    * Show how systems perform under different conditions and allow users to test various ways to model a system or possible approaches to a problem.
* And many more
