on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
   - cron: '0 0 * * *'   # at midnight

name: Compile html docs

jobs:
  build:
    name: Render Rmd files
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      
      - name: Build html files
        run: |
          rmarkdown::render("osca_diagramme.Rmd", output_file="diagramme.html", output_dir = "./docs/")
          rmarkdown::render("om.Rmd", output_file="om.html", output_dir = "./docs/")
          rmarkdown::render("osca.Rmd", output_file="osca.html", output_dir = "./docs/")
        shell: Rscript {0}
        
      - name: Commit results
        run: |
          git config --local user.email "junk@relund.dk"
          git config --local user.name "relund"
          git config pull.rebase false
          git add docs/\*.html
          git commit --allow-empty -am 'gHA build html: ${{github.run_number}}' || echo "No changes to commit"
          git pull origin main
          git push origin || echo "No changes to commit"
