on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Compile html docs

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.osca }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      
      - name: Build html files
        run: |
          gs4_deauth()
          rmarkdown::render("osca_diagramme.Rmd", output_file="diagramme.html", output_dir = "./docs/")
          rmarkdown::render("om.Rmd", output_file="om.html", output_dir = "./docs/")
          rmarkdown::render("osca.Rmd", output_file="osca.html", output_dir = "./docs/")
        Rscript {0}

